### ISSUE TITLE
I'm not able to find this release with jar, please help.

### ISSUE THREAD

**Issue by DrasisDev** [johanwilliams/org.openhab.binding.fibaro#20]
I have created a release with a jar you can download. Just drop it in your openhab addons folder and it should install just fine. Please also review the documentation in the readme for instructions on how to config.

Please note this is just a hobby project and there could be bugs etc. I have not had time to finish the binding to submit it as an official one.

Good luck!

_Originally posted by @johanwilliams in https://github.com/johanwilliams/org.openhab.binding.fibaro/issues/18#issuecomment-401824947_

**Comment by johanwilliams** [comment]
You can find it under code --> Releses (0.9.0)

**Comment by DrasisDev** [comment]
> You can find it under code --> Releses (0.9.0)

Thank you.
